//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAnswerDetail
    {
        public int AnswerDetailID { get; set; }
        public int AnswerId { get; set; }
        public int FormQuestionId { get; set; }
        public string Answer { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual FormAnswer FormAnswer { get; set; }
        public virtual FormQuestion FormQuestion { get; set; }
    }
}
