//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMSDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DynamicFormEntities : DbContext
    {
        public DynamicFormEntities()
            : base("name=DynamicFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DropDownList> DropDownLists { get; set; }
        public virtual DbSet<FormAnswer> FormAnswers { get; set; }
        public virtual DbSet<FormAnswerDetail> FormAnswerDetails { get; set; }
        public virtual DbSet<FormCategory> FormCategories { get; set; }
        public virtual DbSet<FormQuestion> FormQuestions { get; set; }
        public virtual DbSet<InputType> InputTypes { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
    }
}
